apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f .\docker-compose.yml
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: api
  name: api
spec:
  ports:
    - name: "7000"
      port: 7000
      targetPort: 7000
  selector:
    io.kompose.service: api
