version: "3.8"

services:
  api:
    depends_on:
      - db
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - 7000:7000
    environment:
      SPRING_APPLICATION_JSON: >
        {
          "spring.datasource.url" : "jdbc:postgresql://db:5432/${POSTGRES_DB}",
          "spring.datasource.username" : "${POSTGRES_USER}",
          "spring.datasource.password" : "${POSTGRES_PASSWORD}",
          "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.PostgreSQLDialect",
          "spring.jpa.hibernate.ddl-auto" : "create-drop"
        }

  web:
    build: ./frontend
    ports:
      - 3000:3000
    depends_on:
      - api
  db:
    image: postgis/postgis:16-master
    volumes:
      - db:/var/lib/postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    depends_on:
      - web
      - api

volumes:
  db:
