spring:
  application:
    name: MiniProjectWithSecurity

  datasource:
    url: jdbc:postgresql://localhost:5432/miniproj
    username: postgres
    password: helo
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect